name: Deploy

on:
  deployment

jobs:
  deploy-dev:
    name: Deploy to ENVIRONMENT_NAME environment
    if: ${{ github.event.deployment.environment == 'dev' }}
    concurrency: ENVIRONMENT_NAME
    permissions:
      deployments: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Update deployment status (pending)
        if: success()
        uses: chrnorm/deployment-status@v2
        with:
          token: '${{ github.token }}'
          state: 'pending'
          deployment-id: ${{ github.event.deployment.id }}

      - name: Deploy my app
        run: |
          # add your deployment code here
          echo Deploying...
          sleep 10s
          echo Done!

      - name: Update deployment status (success)
        if: success()
        uses: chrnorm/deployment-status@v2
        with:
          token: '${{ github.token }}'
          state: 'success'
          deployment-id: ${{ github.event.deployment.id }}

      - name: Update deployment status (failure)
        if: failure()
        uses: chrnorm/deployment-status@v2
        with:
          token: '${{ github.token }}'
          state: 'failure'
          deployment-id: ${{ github.event.deployment.id }}
