apiVersion: v1
kind: Service
metadata:
  name: flow-manager-service
  annotations:
    mia-platform.eu/version: 14.1.0-alpha.0
  labels:
    app: flow-manager-service
    app.kubernetes.io/name: flow-manager-service
    app.kubernetes.io/version: 2.7.0
    app.kubernetes.io/component: custom
    app.kubernetes.io/part-of: mia-project
    app.kubernetes.io/managed-by: mia-platform
    mia-platform.eu/stage: 'dev'
    mia-platform.eu/tenant: c1d106ff-4716-49a1-88e2-940b21705986
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: null
  selector:
    app: flow-manager-service
